import type { Metadata } from "next";
import { Geist, Geist_Mono, Fira_Code, Crimson_Text } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const firaCode = Fira_Code({ subsets: ['latin'], variable: '--font-fira-code' });
const crimsonText = Crimson_Text({ weight: ['400', '700'], subsets: ['latin'], variable: '--font-crimson-text' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
